/**
 * Language-independent structure + per-language boilerplate used by every
 * demo deed: section headings, labels, fictional parties, and the fictional
 * property schedule. All names, addresses and numbers are invented.
 */

export const LANGUAGES = ["en", "hi", "kn", "mr", "ta", "te"];

/** BCP-47 locales used for date formatting. */
export const LOCALES = {
  en: "en-IN",
  hi: "hi-IN",
  kn: "kn-IN",
  mr: "mr-IN",
  ta: "ta-IN",
  te: "te-IN",
};

/** CSS font stacks per language (Noto families installed at generation time). */
export const FONTS = {
  en: { serif: "'Noto Serif', serif", sans: "'Noto Sans', sans-serif" },
  hi: { serif: "'Noto Serif Devanagari', 'Noto Serif', serif", sans: "'Noto Sans Devanagari', 'Noto Sans', sans-serif" },
  mr: { serif: "'Noto Serif Devanagari', 'Noto Serif', serif", sans: "'Noto Sans Devanagari', 'Noto Sans', sans-serif" },
  kn: { serif: "'Noto Serif Kannada', 'Noto Serif', serif", sans: "'Noto Sans Kannada', 'Noto Sans', sans-serif" },
  ta: { serif: "'Noto Serif Tamil', 'Noto Serif', serif", sans: "'Noto Sans Tamil', 'Noto Sans', sans-serif" },
  te: { serif: "'Noto Serif Telugu', 'Noto Serif', serif", sans: "'Noto Sans Telugu', 'Noto Sans', sans-serif" },
};

export const frame = {
  en: {
    demoWatermark: "DEMO DOCUMENT",
    demoNotice:
      "DEMO DOCUMENT — This is a sample for demonstration purposes only. All names, addresses and details are fictional. Not valid for registration or any legal use.",
    docNoLabel: "Document No.",
    dateLabel: "Date of Execution",
    placeLabel: "Place of Execution",
    stampLabel: "e-Stamp Certificate No.",
    stampValueLabel: "Stamp Duty Paid",
    betweenLabel: "BETWEEN",
    andLabel: "AND",
    witnessethHeading: "NOW THIS DEED WITNESSETH AS FOLLOWS:",
    clausesHeading: "TERMS AND CONDITIONS",
    scheduleHeading: "SCHEDULE OF PROPERTY",
    scheduleFields: {
      surveyNo: "Survey No.",
      extent: "Extent",
      village: "Village",
      taluk: "Taluk",
      district: "District",
      state: "State",
      boundaries: "Bounded on",
      north: "North",
      south: "South",
      east: "East",
      west: "West",
    },
    inWitness:
      "IN WITNESS WHEREOF, the parties hereto have set their hands and signatures on the day, month and year first above written, in the presence of the following witnesses.",
    signaturesHeading: "SIGNATURES",
    witnessesHeading: "WITNESSES",
    witnessLabel: "Witness",
    nameLabel: "Name",
    addressLabel: "Address",
    signatureLabel: "Signature",
    registrationHeading: "REGISTRATION DETAILS (FOR OFFICE USE ONLY)",
    regFields: {
      office: "Office of the Sub-Registrar",
      bookNo: "Book No.",
      documentNo: "Document No.",
      regDate: "Date of Registration",
      subRegistrar: "Sub-Registrar",
      seal: "Seal",
    },
    pageLabel: "Page",
    ofLabel: "of",
  },
  hi: {
    demoWatermark: "DEMO DOCUMENT",
    demoNotice:
      "डेमो दस्तावेज़ — यह केवल प्रदर्शन हेतु नमूना है। सभी नाम, पते और विवरण काल्पनिक हैं। पंजीकरण या किसी कानूनी उपयोग के लिए मान्य नहीं।",
    docNoLabel: "दस्तावेज़ संख्या",
    dateLabel: "निष्पादन की तिथि",
    placeLabel: "निष्पादन का स्थान",
    stampLabel: "ई-स्टाम्प प्रमाणपत्र सं.",
    stampValueLabel: "चुकाई गई स्टाम्प ड्यूटी",
    betweenLabel: "के बीच",
    andLabel: "तथा",
    witnessethHeading: "अब यह विलेख निम्नानुसार साक्षी है:",
    clausesHeading: "नियम एवं शर्तें",
    scheduleHeading: "संपत्ति की अनुसूची",
    scheduleFields: {
      surveyNo: "सर्वे नं.",
      extent: "क्षेत्रफल",
      village: "ग्राम",
      taluk: "तहसील",
      district: "ज़िला",
      state: "राज्य",
      boundaries: "सीमाएं",
      north: "उत्तर",
      south: "दक्षिण",
      east: "पूर्व",
      west: "पश्चिम",
    },
    inWitness:
      "साक्ष्य स्वरूप, पक्षकारों ने उपर्युक्त दिन, माह और वर्ष को निम्नलिखित गवाहों की उपस्थिति में इस विलेख पर हस्ताक्षर किए हैं।",
    signaturesHeading: "हस्ताक्षर",
    witnessesHeading: "गवाह",
    witnessLabel: "गवाह",
    nameLabel: "नाम",
    addressLabel: "पता",
    signatureLabel: "हस्ताक्षर",
    registrationHeading: "पंजीकरण विवरण (केवल कार्यालय उपयोग हेतु)",
    regFields: {
      office: "उप-पंजीयक कार्यालय",
      bookNo: "पुस्तक सं.",
      documentNo: "दस्तावेज़ सं.",
      regDate: "पंजीकरण तिथि",
      subRegistrar: "उप-पंजीयक",
      seal: "मुहर",
    },
    pageLabel: "पृष्ठ",
    ofLabel: "में से",
  },
  kn: {
    demoWatermark: "DEMO DOCUMENT",
    demoNotice:
      "ಡೆಮೊ ದಾಖಲೆ — ಇದು ಪ್ರದರ್ಶನಕ್ಕಾಗಿ ಮಾತ್ರ ಇರುವ ಮಾದರಿ. ಎಲ್ಲಾ ಹೆಸರುಗಳು, ವಿಳಾಸಗಳು ಮತ್ತು ವಿವರಗಳು ಕಾಲ್ಪನಿಕ. ನೋಂದಣಿ ಅಥವಾ ಯಾವುದೇ ಕಾನೂನು ಬಳಕೆಗೆ ಮಾನ್ಯವಲ್ಲ.",
    docNoLabel: "ದಾಖಲೆ ಸಂಖ್ಯೆ",
    dateLabel: "ನಿರ್ವಹಣೆಯ ದಿನಾಂಕ",
    placeLabel: "ನಿರ್ವಹಣೆಯ ಸ್ಥಳ",
    stampLabel: "ಇ-ಸ್ಟಾಂಪ್ ಪ್ರಮಾಣಪತ್ರ ಸಂ.",
    stampValueLabel: "ಪಾವತಿಸಿದ ಮುದ್ರಾಂಕ ಶುಲ್ಕ",
    betweenLabel: "ನಡುವೆ",
    andLabel: "ಮತ್ತು",
    witnessethHeading: "ಈ ಪತ್ರವು ಈ ಕೆಳಗಿನಂತೆ ಸಾಕ್ಷೀಕರಿಸುತ್ತದೆ:",
    clausesHeading: "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
    scheduleHeading: "ಆಸ್ತಿಯ ಅನುಸೂಚಿ",
    scheduleFields: {
      surveyNo: "ಸರ್ವೆ ನಂ.",
      extent: "ವಿಸ್ತೀರ್ಣ",
      village: "ಗ್ರಾಮ",
      taluk: "ತಾಲ್ಲೂಕು",
      district: "ಜಿಲ್ಲೆ",
      state: "ರಾಜ್ಯ",
      boundaries: "ಗಡಿಗಳು",
      north: "ಉತ್ತರ",
      south: "ದಕ್ಷಿಣ",
      east: "ಪೂರ್ವ",
      west: "ಪಶ್ಚಿಮ",
    },
    inWitness:
      "ಸಾಕ್ಷಿಯಾಗಿ, ಪಕ್ಷಕಾರರು ಮೇಲೆ ತಿಳಿಸಿದ ದಿನ, ತಿಂಗಳು ಮತ್ತು ವರ್ಷದಂದು ಕೆಳಗಿನ ಸಾಕ್ಷಿಗಳ ಸಮ್ಮುಖದಲ್ಲಿ ಈ ಪತ್ರಕ್ಕೆ ಸಹಿ ಮಾಡಿದ್ದಾರೆ.",
    signaturesHeading: "ಸಹಿಗಳು",
    witnessesHeading: "ಸಾಕ್ಷಿಗಳು",
    witnessLabel: "ಸಾಕ್ಷಿ",
    nameLabel: "ಹೆಸರು",
    addressLabel: "ವಿಳಾಸ",
    signatureLabel: "ಸಹಿ",
    registrationHeading: "ನೋಂದಣಿ ವಿವರಗಳು (ಕಚೇರಿ ಬಳಕೆಗೆ ಮಾತ್ರ)",
    regFields: {
      office: "ಉಪ-ನೋಂದಣಾಧಿಕಾರಿ ಕಚೇರಿ",
      bookNo: "ಪುಸ್ತಕ ಸಂ.",
      documentNo: "ದಾಖಲೆ ಸಂ.",
      regDate: "ನೋಂದಣಿ ದಿನಾಂಕ",
      subRegistrar: "ಉಪ-ನೋಂದಣಾಧಿಕಾರಿ",
      seal: "ಮುದ್ರೆ",
    },
    pageLabel: "ಪುಟ",
    ofLabel: "ರಲ್ಲಿ",
  },
  mr: {
    demoWatermark: "DEMO DOCUMENT",
    demoNotice:
      "डेमो दस्तऐवज — हा केवळ प्रात्यक्षिकासाठी नमुना आहे. सर्व नावे, पत्ते आणि तपशील काल्पनिक आहेत. नोंदणी किंवा कोणत्याही कायदेशीर वापरासाठी वैध नाही.",
    docNoLabel: "दस्तऐवज क्रमांक",
    dateLabel: "अंमलबजावणीची तारीख",
    placeLabel: "अंमलबजावणीचे ठिकाण",
    stampLabel: "ई-स्टॅम्प प्रमाणपत्र क्र.",
    stampValueLabel: "भरलेली मुद्रांक शुल्क",
    betweenLabel: "यांच्या दरम्यान",
    andLabel: "आणि",
    witnessethHeading: "आता हे पत्र खालीलप्रमाणे साक्ष देते:",
    clausesHeading: "अटी व शर्ती",
    scheduleHeading: "मालमत्तेची अनुसूची",
    scheduleFields: {
      surveyNo: "सर्व्हे क्र.",
      extent: "क्षेत्रफळ",
      village: "गाव",
      taluk: "तालुका",
      district: "जिल्हा",
      state: "राज्य",
      boundaries: "सीमा",
      north: "उत्तर",
      south: "दक्षिण",
      east: "पूर्व",
      west: "पश्चिम",
    },
    inWitness:
      "साक्ष म्हणून, पक्षकारांनी वर नमूद केलेल्या दिवशी, महिन्यात आणि वर्षी खालील साक्षीदारांच्या उपस्थितीत या पत्रावर स्वाक्षऱ्या केल्या आहेत.",
    signaturesHeading: "स्वाक्षऱ्या",
    witnessesHeading: "साक्षीदार",
    witnessLabel: "साक्षीदार",
    nameLabel: "नाव",
    addressLabel: "पत्ता",
    signatureLabel: "स्वाक्षरी",
    registrationHeading: "नोंदणी तपशील (केवळ कार्यालयीन वापरासाठी)",
    regFields: {
      office: "उप-निबंधक कार्यालय",
      bookNo: "पुस्तक क्र.",
      documentNo: "दस्तऐवज क्र.",
      regDate: "नोंदणी दिनांक",
      subRegistrar: "उप-निबंधक",
      seal: "शिक्का",
    },
    pageLabel: "पान",
    ofLabel: "पैकी",
  },
  ta: {
    demoWatermark: "DEMO DOCUMENT",
    demoNotice:
      "டெமோ ஆவணம் — இது காட்சிக்காக மட்டுமே உருவாக்கப்பட்ட மாதிரி. அனைத்துப் பெயர்கள், முகவரிகள் மற்றும் விவரங்கள் கற்பனையானவை. பதிவு அல்லது எந்தச் சட்டப் பயன்பாட்டிற்கும் செல்லாது.",
    docNoLabel: "ஆவண எண்",
    dateLabel: "செயல்படுத்தப்பட்ட தேதி",
    placeLabel: "செயல்படுத்தப்பட்ட இடம்",
    stampLabel: "மின்-முத்திரைச் சான்றிதழ் எண்",
    stampValueLabel: "செலுத்தப்பட்ட முத்திரைக் கட்டணம்",
    betweenLabel: "இடையே",
    andLabel: "மற்றும்",
    witnessethHeading: "இந்தப் பத்திரம் பின்வருமாறு சாட்சியமளிக்கிறது:",
    clausesHeading: "விதிமுறைகளும் நிபந்தனைகளும்",
    scheduleHeading: "சொத்து அட்டவணை",
    scheduleFields: {
      surveyNo: "சர்வே எண்",
      extent: "பரப்பளவு",
      village: "கிராமம்",
      taluk: "வட்டம்",
      district: "மாவட்டம்",
      state: "மாநிலம்",
      boundaries: "எல்லைகள்",
      north: "வடக்கு",
      south: "தெற்கு",
      east: "கிழக்கு",
      west: "மேற்கு",
    },
    inWitness:
      "சாட்சியாக, மேற்குறிப்பிட்ட நாள், மாதம் மற்றும் ஆண்டில், பின்வரும் சாட்சிகளின் முன்னிலையில் தரப்பினர் இந்தப் பத்திரத்தில் கையொப்பமிட்டுள்ளனர்.",
    signaturesHeading: "கையொப்பங்கள்",
    witnessesHeading: "சாட்சிகள்",
    witnessLabel: "சாட்சி",
    nameLabel: "பெயர்",
    addressLabel: "முகவரி",
    signatureLabel: "கையொப்பம்",
    registrationHeading: "பதிவு விவரங்கள் (அலுவலகப் பயன்பாட்டிற்கு மட்டும்)",
    regFields: {
      office: "சார்-பதிவாளர் அலுவலகம்",
      bookNo: "புத்தக எண்",
      documentNo: "ஆவண எண்",
      regDate: "பதிவு தேதி",
      subRegistrar: "சார்-பதிவாளர்",
      seal: "முத்திரை",
    },
    pageLabel: "பக்கம்",
    ofLabel: "இல்",
  },
  te: {
    demoWatermark: "DEMO DOCUMENT",
    demoNotice:
      "డెమో పత్రం — ఇది ప్రదర్శన కోసం మాత్రమే రూపొందించిన నమూనా. అన్ని పేర్లు, చిరునామాలు మరియు వివరాలు కల్పితమైనవి. నమోదు లేదా ఏ చట్టపరమైన ఉపయోగానికీ చెల్లదు.",
    docNoLabel: "పత్రం సంఖ్య",
    dateLabel: "అమలు తేదీ",
    placeLabel: "అమలు స్థలం",
    stampLabel: "ఇ-స్టాంప్ సర్టిఫికేట్ నం.",
    stampValueLabel: "చెల్లించిన స్టాంప్ డ్యూటీ",
    betweenLabel: "మధ్య",
    andLabel: "మరియు",
    witnessethHeading: "ఈ పత్రం ఈ క్రింది విధంగా సాక్ష్యమిస్తుంది:",
    clausesHeading: "నియమాలు మరియు షరతులు",
    scheduleHeading: "ఆస్తి షెడ్యూల్",
    scheduleFields: {
      surveyNo: "సర్వే నం.",
      extent: "విస్తీర్ణం",
      village: "గ్రామం",
      taluk: "మండలం",
      district: "జిల్లా",
      state: "రాష్ట్రం",
      boundaries: "సరిహద్దులు",
      north: "ఉత్తరం",
      south: "దక్షిణం",
      east: "తూర్పు",
      west: "పడమర",
    },
    inWitness:
      "సాక్ష్యంగా, పైన పేర్కొన్న రోజు, నెల మరియు సంవత్సరంలో, క్రింది సాక్షుల సమక్షంలో పక్షాలు ఈ పత్రంపై సంతకాలు చేశారు.",
    signaturesHeading: "సంతకాలు",
    witnessesHeading: "సాక్షులు",
    witnessLabel: "సాక్షి",
    nameLabel: "పేరు",
    addressLabel: "చిరునామా",
    signatureLabel: "సంతకం",
    registrationHeading: "నమోదు వివరాలు (కార్యాలయ వినియోగానికి మాత్రమే)",
    regFields: {
      office: "సబ్-రిజిస్ట్రార్ కార్యాలయం",
      bookNo: "పుస్తకం నం.",
      documentNo: "పత్రం నం.",
      regDate: "నమోదు తేదీ",
      subRegistrar: "సబ్-రిజిస్ట్రార్",
      seal: "ముద్ర",
    },
    pageLabel: "పేజీ",
    ofLabel: "లో",
  },
};

/**
 * Fictional parties reused across the deeds. party1 is the
 * grantor/executant, party2 the grantee/beneficiary.
 */
export const parties = {
  en: {
    party1: { name: "Shri Raghav Anand Kulkarni", parentage: "S/o Late Anand Rao Kulkarni", age: "52 years", address: "No. 14, 3rd Cross, Chandra Layout, Demopura, Bengaluru — 560000" },
    party2: { name: "Smt. Meera Suresh Nair", parentage: "D/o Suresh Kumar Nair", age: "39 years", address: "Flat 7B, Green Meadows Apartments, Lake View Road, Demopura, Bengaluru — 560000" },
    witness1: { name: "Shri Prakash M. Hegde", address: "House No. 22, Temple Street, Demopura" },
    witness2: { name: "Smt. Lakshmi Venkatesh", address: "Plot 5, Garden Enclave, Demopura" },
    place: "Demopura",
  },
  hi: {
    party1: { name: "श्री राघव आनंद कुलकर्णी", parentage: "पुत्र स्व. आनंद राव कुलकर्णी", age: "52 वर्ष", address: "मकान सं. 14, तीसरा क्रॉस, चंद्रा लेआउट, डेमोपुरा, बेंगलुरु — 560000" },
    party2: { name: "श्रीमती मीरा सुरेश नायर", parentage: "पुत्री सुरेश कुमार नायर", age: "39 वर्ष", address: "फ्लैट 7बी, ग्रीन मीडोज अपार्टमेंट, लेक व्यू रोड, डेमोपुरा, बेंगलुरु — 560000" },
    witness1: { name: "श्री प्रकाश एम. हेगड़े", address: "मकान सं. 22, मंदिर मार्ग, डेमोपुरा" },
    witness2: { name: "श्रीमती लक्ष्मी वेंकटेश", address: "प्लॉट 5, गार्डन एन्क्लेव, डेमोपुरा" },
    place: "डेमोपुरा",
  },
  kn: {
    party1: { name: "ಶ್ರೀ ರಾಘವ್ ಆನಂದ್ ಕುಲಕರ್ಣಿ", parentage: "ದಿ. ಆನಂದ್ ರಾವ್ ಕುಲಕರ್ಣಿ ಅವರ ಮಗ", age: "52 ವರ್ಷ", address: "ನಂ. 14, 3ನೇ ಕ್ರಾಸ್, ಚಂದ್ರ ಲೇಔಟ್, ಡೆಮೊಪುರ, ಬೆಂಗಳೂರು — 560000" },
    party2: { name: "ಶ್ರೀಮತಿ ಮೀರಾ ಸುರೇಶ್ ನಾಯರ್", parentage: "ಸುರೇಶ್ ಕುಮಾರ್ ನಾಯರ್ ಅವರ ಮಗಳು", age: "39 ವರ್ಷ", address: "ಫ್ಲಾಟ್ 7ಬಿ, ಗ್ರೀನ್ ಮೆಡೋಸ್ ಅಪಾರ್ಟ್‌ಮೆಂಟ್ಸ್, ಲೇಕ್ ವ್ಯೂ ರಸ್ತೆ, ಡೆಮೊಪುರ, ಬೆಂಗಳೂರು — 560000" },
    witness1: { name: "ಶ್ರೀ ಪ್ರಕಾಶ್ ಎಂ. ಹೆಗಡೆ", address: "ಮನೆ ನಂ. 22, ದೇವಸ್ಥಾನ ಬೀದಿ, ಡೆಮೊಪುರ" },
    witness2: { name: "ಶ್ರೀಮತಿ ಲಕ್ಷ್ಮಿ ವೆಂಕಟೇಶ್", address: "ಪ್ಲಾಟ್ 5, ಗಾರ್ಡನ್ ಎನ್‌ಕ್ಲೇವ್, ಡೆಮೊಪುರ" },
    place: "ಡೆಮೊಪುರ",
  },
  mr: {
    party1: { name: "श्री राघव आनंद कुलकर्णी", parentage: "पुत्र कै. आनंद राव कुलकर्णी", age: "52 वर्षे", address: "घर क्र. 14, तिसरा क्रॉस, चंद्रा लेआउट, डेमोपुरा, बेंगळुरू — 560000" },
    party2: { name: "श्रीमती मीरा सुरेश नायर", parentage: "कन्या सुरेश कुमार नायर", age: "39 वर्षे", address: "फ्लॅट 7बी, ग्रीन मीडोज अपार्टमेंट्स, लेक व्ह्यू रोड, डेमोपुरा, बेंगळुरू — 560000" },
    witness1: { name: "श्री प्रकाश एम. हेगडे", address: "घर क्र. 22, मंदिर मार्ग, डेमोपुरा" },
    witness2: { name: "श्रीमती लक्ष्मी व्यंकटेश", address: "प्लॉट 5, गार्डन एन्क्लेव्ह, डेमोपुरा" },
    place: "डेमोपुरा",
  },
  ta: {
    party1: { name: "திரு. ராகவ் ஆனந்த் குல்கர்ணி", parentage: "மறைந்த ஆனந்த் ராவ் குல்கர்ணியின் மகன்", age: "52 வயது", address: "எண் 14, 3வது குறுக்குத் தெரு, சந்திரா லேஅவுட், டெமோபுரா, பெங்களூரு — 560000" },
    party2: { name: "திருமதி மீரா சுரேஷ் நாயர்", parentage: "சுரேஷ் குமார் நாயரின் மகள்", age: "39 வயது", address: "பிளாட் 7பி, கிரீன் மெடோஸ் அபார்ட்மென்ட்ஸ், லேக் வியூ சாலை, டெமோபுரா, பெங்களூரு — 560000" },
    witness1: { name: "திரு. பிரகாஷ் எம். ஹெக்டே", address: "வீட்டு எண் 22, கோயில் தெரு, டெமோபுரா" },
    witness2: { name: "திருமதி லட்சுமி வெங்கடேஷ்", address: "மனை 5, கார்டன் என்கிளேவ், டெமோபுரா" },
    place: "டெமோபுரா",
  },
  te: {
    party1: { name: "శ్రీ రాఘవ్ ఆనంద్ కులకర్ణి", parentage: "దివంగత ఆనంద్ రావు కులకర్ణి కుమారుడు", age: "52 సంవత్సరాలు", address: "నం. 14, 3వ క్రాస్, చంద్ర లేఅవుట్, డెమోపుర, బెంగళూరు — 560000" },
    party2: { name: "శ్రీమతి మీరా సురేష్ నాయర్", parentage: "సురేష్ కుమార్ నాయర్ కుమార్తె", age: "39 సంవత్సరాలు", address: "ఫ్లాట్ 7బి, గ్రీన్ మెడోస్ అపార్ట్‌మెంట్స్, లేక్ వ్యూ రోడ్, డెమోపుర, బెంగళూరు — 560000" },
    witness1: { name: "శ్రీ ప్రకాష్ ఎం. హెగ్డే", address: "ఇంటి నం. 22, ఆలయ వీధి, డెమోపుర" },
    witness2: { name: "శ్రీమతి లక్ష్మి వెంకటేష్", address: "ప్లాట్ 5, గార్డెన్ ఎన్‌క్లేవ్, డెమోపుర" },
    place: "డెమోపుర",
  },
};

/** Fictional property schedule reused across the deeds. */
export const schedule = {
  en: { surveyNo: "127/2A", extent: "2,400 sq. ft. (site) with a building of 1,850 sq. ft.", village: "Demopura", taluk: "Demo Taluk", district: "Demo District", state: "Karnataka", north: "Property of Shri Mohan Das (S. No. 127/1)", south: "30 ft. wide public road", east: "Property of Smt. Radha Bai (S. No. 127/2B)", west: "Storm-water drain and vacant site" },
  hi: { surveyNo: "127/2ए", extent: "2,400 वर्ग फुट (भूखंड) एवं 1,850 वर्ग फुट का भवन", village: "डेमोपुरा", taluk: "डेमो तहसील", district: "डेमो ज़िला", state: "कर्नाटक", north: "श्री मोहन दास की संपत्ति (स. नं. 127/1)", south: "30 फुट चौड़ी सार्वजनिक सड़क", east: "श्रीमती राधा बाई की संपत्ति (स. नं. 127/2बी)", west: "नाला एवं खाली भूखंड" },
  kn: { surveyNo: "127/2ಎ", extent: "2,400 ಚ. ಅಡಿ (ನಿವೇಶನ) ಮತ್ತು 1,850 ಚ. ಅಡಿ ಕಟ್ಟಡ", village: "ಡೆಮೊಪುರ", taluk: "ಡೆಮೊ ತಾಲ್ಲೂಕು", district: "ಡೆಮೊ ಜಿಲ್ಲೆ", state: "ಕರ್ನಾಟಕ", north: "ಶ್ರೀ ಮೋಹನ್ ದಾಸ್ ಅವರ ಆಸ್ತಿ (ಸ. ನಂ. 127/1)", south: "30 ಅಡಿ ಅಗಲದ ಸಾರ್ವಜನಿಕ ರಸ್ತೆ", east: "ಶ್ರೀಮತಿ ರಾಧಾ ಬಾಯಿ ಅವರ ಆಸ್ತಿ (ಸ. ನಂ. 127/2ಬಿ)", west: "ಮಳೆನೀರು ಚರಂಡಿ ಮತ್ತು ಖಾಲಿ ನಿವೇಶನ" },
  mr: { surveyNo: "127/2ए", extent: "2,400 चौ. फूट (भूखंड) व 1,850 चौ. फूट इमारत", village: "डेमोपुरा", taluk: "डेमो तालुका", district: "डेमो जिल्हा", state: "कर्नाटक", north: "श्री मोहन दास यांची मालमत्ता (स. क्र. 127/1)", south: "30 फूट रुंद सार्वजनिक रस्ता", east: "श्रीमती राधा बाई यांची मालमत्ता (स. क्र. 127/2बी)", west: "पावसाळी नाला व रिकामा भूखंड" },
  ta: { surveyNo: "127/2ஏ", extent: "2,400 ச. அடி (மனை) மற்றும் 1,850 ச. அடி கட்டிடம்", village: "டெமோபுரா", taluk: "டெமோ வட்டம்", district: "டெமோ மாவட்டம்", state: "கர்நாடகா", north: "திரு. மோகன் தாஸ் அவர்களின் சொத்து (ச. எண் 127/1)", south: "30 அடி அகல பொதுச் சாலை", east: "திருமதி ராதா பாய் அவர்களின் சொத்து (ச. எண் 127/2பி)", west: "மழைநீர் வாய்க்கால் மற்றும் காலி மனை" },
  te: { surveyNo: "127/2ఎ", extent: "2,400 చ. అడుగులు (స్థలం) మరియు 1,850 చ. అడుగుల భవనం", village: "డెమోపుర", taluk: "డెమో మండలం", district: "డెమో జిల్లా", state: "కర్ణాటక", north: "శ్రీ మోహన్ దాస్ ఆస్తి (స. నం. 127/1)", south: "30 అడుగుల వెడల్పు ప్రజా రహదారి", east: "శ్రీమతి రాధా బాయి ఆస్తి (స. నం. 127/2బి)", west: "వర్షపు నీటి కాలువ మరియు ఖాళీ స్థలం" },
};
